# Generated by Django 2.0.2 on 2018-03-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=30)),
                ('keep_latest', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='RssOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('feed_base_url', models.URLField()),
                ('feed_output_file_name', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='download_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_options', to='tools.RssOptions'),
        ),
        migrations.AddField(
            model_name='channel',
            name='rss_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_options', to='tools.RssOptions'),
        ),
    ]
